ZhongAnTech/zarm

components/Input/Input.jsx

修复了2处：
textarea设置defaultValue的时候console会有一个warning。
另外autosize在display:none转变为可见的情况下会有一个bug

fix input textarea issue

---

package.json

classnames as dependency

---

components/Mask/index.native.tsx
components/Mask/style/index.native.tsx
components/Popup/index.native.tsx
components/Popup/style/index.native.tsx
components/index.native.tsx
examples-rn/demoList.js
examples-rn/pages/PopupPage.js

Popup and Mask

---

.gitignore
components/Accordion/Item.tsx
components/Accordion/PropsType.tsx
components/Accordion/__tests__/__snapshots__/index.test.jsx.snap
components/Accordion/__tests__/index.test.jsx
components/Accordion/index.tsx
components/Accordion/style/component.scss
components/Accordion/style/index.scss
components/Accordion/style/index.tsx
components/Input/__tests__/__snapshots__/index.test.jsx.snap
components/index.tsx
components/style/themes/default.scss
docs/zh-cn/SUMMARY.md
docs/zh-cn/components/Accordion.md
examples/components/App.jsx
examples/pages/AccordionPage.jsx
examples/pages/Index.jsx

feat: add Accordion Component

---

components/Accordion/Accordion.tsx
components/Accordion/AccordionItem.tsx
components/Accordion/PropsType.tsx
components/Accordion/__tests__/__snapshots__/index.test.jsx.snap
components/Accordion/__tests__/index.test.jsx
components/Accordion/style/component.scss
components/DateSelect/__tests__/__snapshots__/index.test.jsx.snap
docs/zh-cn/components/Accordion.md
examples/pages/AccordionPage.jsx

- 优化边框重叠粗细不一致的问题
- 增加强制展开模式（默认展开且不可收缩）
- 修改单元测试用例，增加测试覆盖率
- 修改accordion属性名为multiple
- 修复测试用例在node@6.10.x下报错的问题

Accordion 组件优化

---

components/ActionSheet/index.native.tsx
components/ActionSheet/style/index.native.tsx
components/Popup/style/index.native.tsx
components/index.native.tsx
examples-rn/demoList.js
examples-rn/pages/ActionSheet.js

1 add actionsheet component;
2 update popup style, so that it can be better used in other component;

components++: ActionSheet

---

components/SwipeAction/index.native.tsx
components/SwipeAction/style/index.native.tsx
components/index.native.tsx
examples-rn/demoList.js
examples-rn/pages/SwipeActionPage.js

增加SwipeAction组件

---

components/FilePicker/PropsType.tsx
components/FilePicker/index.native.tsx
components/FilePicker/style/index.native.tsx
components/NavBar/PropsType.tsx
components/NavBar/index.native.tsx
components/NavBar/style/index.native.tsx
components/index.native.tsx
examples-rn/demoList.js
examples-rn/ios/zarm.xcodeproj/project.pbxproj
examples-rn/ios/zarm/Info.plist
examples-rn/pages/FilePicker.js
package.json

本地图片展示使用第三方组件 react-native-camera-roll-picker；

feat: 图片选择组件、导航栏

---

README.md

docs: add a blank space for gitpull

---

components/style/themes/default.scss
components/switch/PropsType.tsx
components/switch/__tests__/__snapshots__/index.test.jsx.snap
components/switch/__tests__/index.test.jsx
components/switch/demo.md
components/switch/index.tsx
components/switch/style/component.scss
components/switch/style/mixins.scss

perf: update switch component

---

components/picker-view/PropsType.tsx
components/picker-view/index.tsx
components/picker/Picker.tsx
components/picker/__tests__/__snapshots__/index.test.jsx.snap
components/picker/demo.md
components/popup/Portal.tsx
components/select/__tests__/__snapshots__/index.test.jsx.snap
components/select/index.tsx
components/utils/getState.tsx
components/wheel/Wheel.tsx

重构select、picker、picker-view组件。
将上述组件的onInit方法去除，提取getState为公共方法。

fix: refactor select & picker & picker-view

---

components/toast/index.tsx

fix: toast compatiable with ssr

---

components/keyboard/Keyboard.tsx
components/keyboard/PropsType.tsx
components/locale-provider/LocaleProvider.tsx
components/locale-provider/LocaleReceiver.tsx
components/picker/Picker.tsx
components/picker/PropsType.tsx
components/select/Select.tsx

chore: add type restrictions on LocaleReceiver

---

components/file-picker/__tests__/__snapshots__/index.test.jsx.snap
components/file-picker/__tests__/index.test.jsx
components/file-picker/utils/createThumbnail.tsx
components/file-picker/utils/handleFileInfo.tsx

 refactor: promise version

---

components/alert/Alert.tsx
components/confirm/Confirm.tsx
components/locale-provider/LocaleProvider.tsx

1. Alert.show 支持国际化，Confirm.show 支持国际化

Alert等组件静态方法调用支持国际化

---

components/alert/__tests__/index.test.jsx
components/confirm/__tests__/index.test.jsx

1. Alert.show 增加单元测试，Confirm.show 增加单元测试

Alert等组件增加单元测试

---

components/action-sheet/index.tsx
components/alert/index.tsx
components/confirm/index.tsx
components/date-picker-view/index.tsx
components/date-picker/index.tsx
components/date-select/index.tsx
components/index.tsx
components/keyboard/index.tsx
components/locale-provider/index.tsx
components/locale-receiver/LocaleReceiver.tsx
components/locale-receiver/index.tsx
components/locale-receiver/style/index.tsx
components/picker/index.tsx
components/pull/index.tsx
components/search-bar/index.tsx
components/select/index.tsx

- 增加locale-receiver目录，并修改相关的引用路径

LocaleReceiver移到外层作为独立组件对外输出

---

components/locale-provider/__tests__/__snapshots__/index.test.jsx.snap
components/locale-provider/__tests__/index.test.jsx
components/locale-provider/demo.md
components/modal/index.tsx

fix: locale-provider demo

---

components/popper/__tests__/__snapshots__/index.test.jsx.snap
components/popper/demo.md
components/popper/index.tsx
components/style/animations/menu-slide.scss
components/style/animations/zoom-fade.scss

chore: update popper animation name

---

components/popper/index.tsx
components/utils/canUseDom.tsx

test: add check with dom for popper

test: add check with dom for popper

---

components/image-preview/style/component.scss
components/pinch-zoom/style/component.scss

fix: ImagePreview show long images can't scroll

---

components/__tests__/index.native.test.ts
components/__tests__/index.test.ts

barrel files: `src/components/index.ts` and `src/components/index.native.ts`

test: add snapshot tests for barrel file

---

components/utils/__tests__/date.test.ts
components/utils/date.tsx

- Added more unit tests
- Improved code test coverage to 100%
- Improve TS types

Test/add more unit tests for  date util

---

components/date-picker-view/utils/parseState.tsx

fix [#603](https://github.com/ZhongAnTech/zarm/issues/603)

fix: invalid date in time mode datePicker

---

packages/zarm/src/config-provider/ConfigProvider.tsx

fix: 修复 ConfigProvider 服务端渲染报错

---

packages/zarm/src/tooltip/index.tsx
packages/zarm/src/tooltip/interface.ts

feat(tooltip): 优化tooltip

---

.eslintrc.js
packages/site/demo/styles/GridPage.scss
packages/site/site.config.js
packages/zarm/src/grid/Grid.tsx
packages/zarm/src/grid/GridContext.ts
packages/zarm/src/grid/Item.tsx
packages/zarm/src/grid/__tests__/__snapshots__/index.test.tsx.snap
packages/zarm/src/grid/__tests__/index.test.tsx
packages/zarm/src/grid/demo.md
packages/zarm/src/grid/demo.scss
packages/zarm/src/grid/index.ts
packages/zarm/src/grid/interface.ts
packages/zarm/src/grid/style/index.scss
packages/zarm/src/grid/style/index.ts
packages/zarm/src/index.ts
packages/zarm/src/n-config-provider/setTheme.ts
packages/zarm/src/style/components.scss
packages/zarm/src/style/core/mixins/index.scss
packages/zarm/src/style/themes/default.scss
packages/zarm/src/utils/types.d.ts

feat: 新增宫格组件

---

packages/zarm/src/tabs/Tabs.tsx
packages/zarm/src/tabs/demo.md

根据条件动态渲染Tabs的children后需要重新计算下划线长度

根据条件动态渲染Tabs的children后需要重新计算下划线长度

---

packages/zarm/src/notice-bar/demo.md

docs(NoticeBar): 展示三种样式

---

packages/zarm/src/panel/demo.md
packages/zarm/src/panel/index.tsx
packages/zarm/src/panel/interface.ts
packages/zarm/src/panel/style/component.scss

1. 新增`bordered`属性，控制Panel内容区域是否有边框
2. 完善`ref` TS type

feat(Panel): 新增bordered prop，控制Panel内容区域是否有边框

---

packages/site/web/docs/migration-v3.md

docs: fix some error
